spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888" # Connect to Config Server

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.1
        max-interval: 2000
