spring:
  application:
    name: eureka-server
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6 # Số lần thử lại tối đa
        initial-interval: 1000 # Chờ 1 giây trước lần thử đầu tiên
        multiplier: 1.1 # Tăng thời gian chờ mỗi lần thử
        max-interval: 2000 # Thời gian chờ tối đa giữa các lần thử