server:
  port: 8888 # Port chuẩn cho Config Server

spring:
  application:
    name: config-server # Tên định danh của chính Config Server
  profiles:
    # Thay đổi profile active từ 'git' sang 'native'
    active: native
  cloud:
    config:
      server:
        # Cấu hình cho profile 'native'
        native:
          # Chỉ định đường dẫn tương đối đến thư mục chứa config
          # '${user.dir}' tham chiếu đến thư mục gốc của dự án nơi lệnh được chạy
          search-locations: file:///${user.dir}/local-config-repo
eureka:
  client:
    # Config server không cần đăng ký với Eureka
    enabled: false
